version: '3'

services:

  dvc-2-iris-demo:
    build:
      context: .
      args:
        GIT_CONFIG_USER_NAME: $GIT_CONFIG_USER_NAME
        GIT_CONFIG_EMAIL: $GIT_CONFIG_EMAIL
    image: dvc-2-iris-demo:latest
    env_file:
      - .env
    environment:
      PYTHONPATH: '/home/dvc-5-demo-project-iris'
      LANG: 'C.UTF-8'
    ports:
      - 8888:8888
    volumes:
      - ./:/home/dvc-5-demo-project-iris