project: 7labs/dvc-2-iris-demo
name: vision
tags: [solution-0-prototype, dev]



dataset:

  # random state for train/test split
  random_state: 42
  # source dataset
  dataset_csv: data/raw/iris.csv
  featured_dataset_csv: data/interim/featured_iris.csv
  train_csv: data/processed/train_iris.csv
  test_csv: data/processed/test_iris.csv
  test_size: 0.2
  features_columns_range: ['sepal_length', 'petal_length_to_petal_width']
  target_column: species


train:
  # available estimators:
  #     logreg (sklearn.linear_model.LogisticRegression),
  #     smv(sklearn.svm.SVC),
  #     knn(sklearn.neighbors.KNeighborsClassifier)
  estimator_name: 'knn'
  # params of GridSearchCV constructor
  grid_search_cv_config:
    # grid of estimator parameters (see in https://scikit-learn.org/ for specific estimator
    param_grid:
      n_neighbors: [5,10,15]
      leaf_size: [30,60,90]
      p: [1,2]
    cv: 10


evaluate:
  metrics_file: eval.txt


model:

  model_name: model.joblib
  models_folder: models


report:
  reports_folder: experiments


split_config:
  folder: experiments
